# Generated by Django 3.2.4 on 2021-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('module', '0002_auto_20210617_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quizzes',
            field=models.ManyToManyField(to='quiz.Quizzes'),
        ),
    ]
